name: DeploybPieceOfTheater FrameworkDependant

on:
  push:
    tags:
        - "release/v*"

env:
    PROJECT_PATH: PieceOfTheater.Wpf/PieceOfTheater.Wpf.csproj        

jobs:
    deploy:
        runs-on: windows-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 6.0.x

        - name: Restore
          run: dotnet restore ${{ env.PROJECT_PATH }}

        - name: Publish
          run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true

        - name: Create release
          uses: actions/create-release@v1
          id: create_release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }} (framework dependant)
            draft: false
            prerelease: false
        
        - name: Copy assets
          uses: csexton/release-asset-action@v2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN}}
            pattern: PieceOfTheater.Wpf/bin/Release/net6.0-windows/win-x64/publish/*.*
            release-url: ${{ steps.create_release.outputs.upload_url }}












